development: &default
  adapter: postgresql
  database: kinscape_development_live
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

test:
  <<: *default
  database: kinscape_test

